"""add google calendar meet integration

Revision ID: 04252077c89b
Revises: c1cbfe12edcf
Create Date: 2026-09-10 15:26:47.184272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '04252077c89b'
down_revision: Union[str, Sequence[str], None] = 'c1cbfe12edcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_connections',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('connected_by_user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('google_account_email', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_google_calendar_connection_tenant')
    )
    with op.batch_alter_table('google_calendar_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_google_calendar_connections_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('google_event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meet_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column(
            'meeting_status', sa.Enum('NOT_CREATED', 'CREATED', 'FAILED', 'CANCELLED', name='meetingstatus'),
            nullable=False, server_default='NOT_CREATED',
        ))

    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.alter_column('meeting_status', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_column('meeting_status')
        batch_op.drop_column('google_calendar_id')
        batch_op.drop_column('meet_link')
        batch_op.drop_column('google_event_id')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('google_calendar_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_google_calendar_connections_tenant_id'))

    op.drop_table('google_calendar_connections')
    # ### end Alembic commands ###
