"""add fee billing module and referral fields

Revision ID: 10616272b8b1
Revises: 13101ee3376f
Create Date: 2026-08-24 10:48:13.315580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '10616272b8b1'
down_revision: Union[str, Sequence[str], None] = '13101ee3376f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_plans',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('class_grade_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_grade_id'], ['class_grades.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'class_grade_id', 'academic_year', name='uq_fee_plan_tenant_class_year')
    )
    with op.batch_alter_table('fee_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_plans_class_grade_id'), ['class_grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_plans_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('invoices',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('class_grade_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('invoice_type', sa.Enum('TUITION', 'ADMISSION', 'OTHER', name='invoicetype'), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'OVERDUE', 'WAIVED', name='invoicestatus'), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_grade_id'], ['class_grades.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'student_id', 'invoice_type', 'period_month', 'period_year', name='uq_invoice_tenant_student_type_period')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_class_grade_id'), ['class_grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('payments',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('JAZZCASH', 'EASYPAISA', 'NAYAPAY', 'SADAPAY', 'BANK_TRANSFER', 'CASH', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('reference_note', sa.String(length=255), nullable=True),
    sa.Column('receipt_image_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_by_user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='paymentverificationstatus'), nullable=False),
    sa.Column('verified_by_user_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('student_admission_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by_family_id', app.models.mixins.GUID(), nullable=True))
        batch_op.add_column(sa.Column('referral_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('referral_note', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(
            'fk_admission_detail_referred_by_family_id', 'families', ['referred_by_family_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_admission_details', schema=None) as batch_op:
        batch_op.drop_constraint('fk_admission_detail_referred_by_family_id', type_='foreignkey')
        batch_op.drop_column('referral_note')
        batch_op.drop_column('referral_discount_amount')
        batch_op.drop_column('referred_by_family_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_student_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_class_grade_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('fee_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_fee_plans_class_grade_id'))

    op.drop_table('fee_plans')
    # ### end Alembic commands ###
