"""add class scheduling and attendance modules

Revision ID: 13101ee3376f
Revises: 94883f799a2c
Create Date: 2026-08-24 10:08:57.248421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '13101ee3376f'
down_revision: Union[str, Sequence[str], None] = '94883f799a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_schedules',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('section_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('subject_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('default_meeting_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_schedules_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_schedules_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_schedules_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_schedules_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('class_sessions',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('class_schedule_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('section_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('subject_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_schedule_id'], ['class_schedules.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'class_schedule_id', 'session_date', name='uq_session_schedule_date')
    )
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_sessions_class_schedule_id'), ['class_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_sessions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('attendance',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('class_session_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('marked_by_user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'class_session_id', 'student_id', name='uq_attendance_session_student')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_class_session_id'), ['class_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_class_session_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('class_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_subject_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_section_id'))
        batch_op.drop_index(batch_op.f('ix_class_sessions_class_schedule_id'))

    op.drop_table('class_sessions')
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_schedules_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_class_schedules_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_schedules_subject_id'))
        batch_op.drop_index(batch_op.f('ix_class_schedules_section_id'))

    op.drop_table('class_schedules')
    # ### end Alembic commands ###
