"""add teacher and staff attendance

Revision ID: 1ec3eb314bf3
Revises: 04252077c89b
Create Date: 2026-09-10 18:49:08.127471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '1ec3eb314bf3'
down_revision: Union[str, Sequence[str], None] = '04252077c89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_attendances',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('staff_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'LEAVE', name='hrattendancestatus'), nullable=False),
    sa.Column('marked_by_user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'staff_id', 'attendance_date', name='uq_staff_attendance_tenant_staff_date')
    )
    with op.batch_alter_table('staff_attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_attendances_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendances_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendances_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('teacher_attendances',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'LEAVE', name='hrattendancestatus'), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marked_by_user_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'teacher_id', 'attendance_date', name='uq_teacher_attendance_tenant_teacher_date')
    )
    with op.batch_alter_table('teacher_attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_attendances_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_attendances_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_attendances_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_attendances_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_attendances_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_attendances_attendance_date'))

    op.drop_table('teacher_attendances')
    with op.batch_alter_table('staff_attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_attendances_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_staff_attendances_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_attendances_attendance_date'))

    op.drop_table('staff_attendances')
    # ### end Alembic commands ###
