"""add families and student admission/withdrawal fields

Revision ID: 2d63e1888a13
Revises: cdf4d6bf1611
Create Date: 2026-08-04 15:25:11.783713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '2d63e1888a13'
down_revision: Union[str, Sequence[str], None] = 'cdf4d6bf1611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('family_number', sa.String(length=20), nullable=False),
    sa.Column('family_name', sa.String(length=255), nullable=False),
    sa.Column('cnic', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'family_number', name='uq_family_tenant_number')
    )
    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_families_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', app.models.mixins.GUID(), nullable=True))
        batch_op.add_column(sa.Column('admission_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('withdrawal_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('withdrawal_reason', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_profiles_family_id'), ['family_id'], unique=False)
        batch_op.create_unique_constraint('uq_student_tenant_admission_number', ['tenant_id', 'admission_number'])
        batch_op.create_foreign_key(
            'fk_student_profiles_family_id_families', 'families', ['family_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_profiles_family_id_families', type_='foreignkey')
        batch_op.drop_constraint('uq_student_tenant_admission_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_student_profiles_family_id'))
        batch_op.drop_column('withdrawal_reason')
        batch_op.drop_column('withdrawal_date')
        batch_op.drop_column('admission_number')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('families', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_families_tenant_id'))

    op.drop_table('families')
    # ### end Alembic commands ###
