"""add teacher payout module

Revision ID: 4125febd46b8
Revises: a9844c95f4be
Create Date: 2026-08-24 12:25:01.707388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '4125febd46b8'
down_revision: Union[str, Sequence[str], None] = 'a9844c95f4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_payout_rates',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('subject_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('rate_type', sa.Enum('PER_SESSION', 'REVENUE_SHARE_PERCENT', name='payoutratetype'), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teacher_payout_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_payout_rates_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_payout_rates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('teacher_payouts',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('sessions_delivered', sa.Integer(), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PAID', name='payoutstatus'), nullable=False),
    sa.Column('approved_by_user_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'teacher_id', 'period_month', 'period_year', name='uq_payout_teacher_period')
    )
    with op.batch_alter_table('teacher_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_payouts_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_payouts_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_payouts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_payouts_teacher_id'))

    op.drop_table('teacher_payouts')
    with op.batch_alter_table('teacher_payout_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_payout_rates_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_payout_rates_teacher_id'))

    op.drop_table('teacher_payout_rates')
    # ### end Alembic commands ###
