"""add notification log module

Revision ID: 4b28b8f0c459
Revises: 4125febd46b8
Create Date: 2026-08-26 01:59:45.080436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '4b28b8f0c459'
down_revision: Union[str, Sequence[str], None] = '4125febd46b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', name='notificationchannel'), nullable=False),
    sa.Column('event', sa.Enum('ATTENDANCE_ABSENT', 'PAYMENT_VERIFIED', 'FEE_DUE_REMINDER', name='notificationevent'), nullable=False),
    sa.Column('recipient_user_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=30), nullable=True),
    sa.Column('student_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'SKIPPED', name='notificationstatus'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_student_id'))

    op.drop_table('notification_logs')
    # ### end Alembic commands ###
