"""add student admission details

Revision ID: 94883f799a2c
Revises: d57a733fc6b9
Create Date: 2026-08-04 18:53:37.965502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = '94883f799a2c'
down_revision: Union[str, Sequence[str], None] = 'd57a733fc6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_admission_details',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('father_cnic', sa.String(length=30), nullable=True),
    sa.Column('father_mobile', sa.String(length=30), nullable=True),
    sa.Column('father_qualification', sa.String(length=255), nullable=True),
    sa.Column('father_occupation', sa.String(length=255), nullable=True),
    sa.Column('guardian_mobile', sa.String(length=30), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('student_cnic', sa.String(length=30), nullable=True),
    sa.Column('caste', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('current_address', sa.String(length=500), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('mother_cnic', sa.String(length=30), nullable=True),
    sa.Column('mother_mobile', sa.String(length=30), nullable=True),
    sa.Column('mother_qualification', sa.String(length=255), nullable=True),
    sa.Column('guardian_relation', sa.String(length=100), nullable=True),
    sa.Column('emergency_relation', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_phone', sa.String(length=30), nullable=True),
    sa.Column('emergency_mobile', sa.String(length=30), nullable=True),
    sa.Column('emergency_address', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('admission_form_number', sa.String(length=50), nullable=True),
    sa.Column('register_serial_no', sa.String(length=50), nullable=True),
    sa.Column('previous_class', sa.String(length=100), nullable=True),
    sa.Column('previous_school', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('student_mobile', sa.String(length=30), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_admission_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_admission_details_student_id'), ['student_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_admission_details_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_admission_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_admission_details_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_student_admission_details_student_id'))

    op.drop_table('student_admission_details')
    # ### end Alembic commands ###
