"""add quiz module

Revision ID: a9844c95f4be
Revises: df8b8cbd3287
Create Date: 2026-08-24 12:03:48.687934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'a9844c95f4be'
down_revision: Union[str, Sequence[str], None] = 'df8b8cbd3287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('section_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('subject_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('quiz_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', name='attemptstatus'), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'quiz_id', 'student_id', name='uq_attempt_quiz_student')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('quiz_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ_SINGLE', 'TRUE_FALSE', name='questiontype'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_questions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quiz_options',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('question_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('option_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_options_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_options_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('quiz_answers',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('attempt_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('question_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('selected_option_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quiz_options.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'attempt_id', 'question_id', name='uq_answer_attempt_question')
    )
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_answers_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_answers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_answers_attempt_id'))

    op.drop_table('quiz_answers')
    with op.batch_alter_table('quiz_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_options_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_options_question_id'))

    op.drop_table('quiz_options')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_student_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_quiz_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_quizzes_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_quizzes_subject_id'))
        batch_op.drop_index(batch_op.f('ix_quizzes_section_id'))

    op.drop_table('quizzes')
    # ### end Alembic commands ###
