"""initial schema: tenants, users, profiles

Revision ID: b758a1927ea7
Revises: 
Create Date: 2026-08-03 12:20:34.479992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = 'b758a1927ea7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', 'PARENT', name='roleenum'), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('admin_profiles',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('parent_profiles',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False),
    sa.Column('sms_opt_in', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('class_grade_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('section_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_class_grade_id'), ['class_grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('teacher_profiles',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('parent_student_links',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('parent_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('relationship_label', sa.String(length=50), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_profiles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    with op.batch_alter_table('parent_student_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_student_links_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_student_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_student_links_tenant_id'))

    op.drop_table('parent_student_links')
    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_tenant_id'))

    op.drop_table('teacher_profiles')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_class_grade_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_profiles_tenant_id'))

    op.drop_table('parent_profiles')
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_profiles_tenant_id'))

    op.drop_table('admin_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
