"""add jazzcash gateway transactions

Revision ID: c1cbfe12edcf
Revises: c4d8f1a6b937
Create Date: 2026-09-10 12:52:08.803554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'c1cbfe12edcf'
down_revision: Union[str, Sequence[str], None] = 'c4d8f1a6b937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_transactions',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('initiated_by_user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('gateway', sa.Enum('JAZZCASH', name='paymentgateway'), nullable=False),
    sa.Column('txn_ref_no', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'COMPLETED', 'FAILED', name='gatewaytransactionstatus'), nullable=False),
    sa.Column('gateway_response_code', sa.String(length=10), nullable=True),
    sa.Column('gateway_response_message', sa.String(length=255), nullable=True),
    sa.Column('gateway_txn_id', sa.String(length=100), nullable=True),
    sa.Column('payment_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gateway_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gateway_transactions_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gateway_transactions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gateway_transactions_txn_ref_no'), ['txn_ref_no'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gateway_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gateway_transactions_txn_ref_no'))
        batch_op.drop_index(batch_op.f('ix_gateway_transactions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_gateway_transactions_invoice_id'))

    op.drop_table('gateway_transactions')
    # ### end Alembic commands ###
