"""add academic years and course hierarchy (courses, teacher assignments, course enrollments)

Revision ID: c3d8e5f7a112
Revises: f2a7c9d13e05
Create Date: 2026-08-26 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'c3d8e5f7a112'
down_revision: Union[str, Sequence[str], None] = 'f2a7c9d13e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'academic_years',
        sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('name', sa.String(length=20), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'name', name='uq_academic_year_tenant_name'),
    )
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_years_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('class_grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', app.models.mixins.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_class_grades_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_class_grades_academic_year_id', 'academic_years', ['academic_year_id'], ['id']
        )

    op.create_table(
        'courses',
        sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('academic_year_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('class_grade_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('section_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('subject_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id']),
        sa.ForeignKeyConstraint(['class_grade_id'], ['class_grades.id']),
        sa.ForeignKeyConstraint(['section_id'], ['sections.id']),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('academic_year_id', 'section_id', 'subject_id', name='uq_course_year_section_subject'),
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_class_grade_id'), ['class_grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_subject_id'), ['subject_id'], unique=False)

    op.create_table(
        'teacher_assignments',
        sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('course_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('assigned_date', sa.Date(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id']),
        sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('course_id', 'teacher_id', name='uq_teacher_assignment_course_teacher'),
    )
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_assignments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table(
        'course_enrollments',
        sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('course_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('enrolled_date', sa.Date(), nullable=False),
        sa.Column('status', sa.Enum('ACTIVE', 'DROPPED', name='enrollmentstatus'), nullable=False),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id']),
        sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('course_id', 'student_id', name='uq_course_enrollment_course_student'),
    )
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_enrollments_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_enrollments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_enrollments_student_id'), ['student_id'], unique=False)

    # TeacherSubject/TeacherSection were never populated by any code path (confirmed dead across
    # every module built on top of them) — Course + TeacherAssignment replace their original intent.
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_subjects_tenant_id'))
    op.drop_table('teacher_subjects')

    with op.batch_alter_table('teacher_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_sections_tenant_id'))
    op.drop_table('teacher_sections')


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table(
        'teacher_sections',
        sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('section_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['section_id'], ['sections.id']),
        sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('teacher_id', 'section_id', name='uq_teacher_section'),
    )
    with op.batch_alter_table('teacher_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_sections_tenant_id'), ['tenant_id'], unique=False)

    op.create_table(
        'teacher_subjects',
        sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('subject_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id']),
        sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('teacher_id', 'subject_id', name='uq_teacher_subject'),
    )
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_subjects_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_course_enrollments_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_enrollments_tenant_id'))
    op.drop_table('course_enrollments')

    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_course_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_tenant_id'))
    op.drop_table('teacher_assignments')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_subject_id'))
        batch_op.drop_index(batch_op.f('ix_courses_section_id'))
        batch_op.drop_index(batch_op.f('ix_courses_class_grade_id'))
        batch_op.drop_index(batch_op.f('ix_courses_academic_year_id'))
        batch_op.drop_index(batch_op.f('ix_courses_tenant_id'))
    op.drop_table('courses')

    with op.batch_alter_table('class_grades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_class_grades_academic_year_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_class_grades_academic_year_id'))
        batch_op.drop_column('academic_year_id')

    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_years_tenant_id'))
    op.drop_table('academic_years')
