"""add academic structure and student class/section FKs

Revision ID: cdf4d6bf1611
Revises: b758a1927ea7
Create Date: 2026-08-03 16:32:55.101648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins


# revision identifiers, used by Alembic.
revision: str = 'cdf4d6bf1611'
down_revision: Union[str, Sequence[str], None] = 'b758a1927ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_grades',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'academic_year', name='uq_class_grade_tenant_name_year')
    )
    with op.batch_alter_table('class_grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_grades_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sections',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('class_grade_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_grade_id'], ['class_grades.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_grade_id', 'name', name='uq_section_class_name')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_class_grade_id'), ['class_grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('subjects',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('class_grade_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_grade_id'], ['class_grades.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_grade_id', 'code', name='uq_subject_class_code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_class_grade_id'), ['class_grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('teacher_sections',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('section_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'section_id', name='uq_teacher_section')
    )
    with op.batch_alter_table('teacher_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_sections_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('teacher_subjects',
    sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('subject_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'subject_id', name='uq_teacher_subject')
    )
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_subjects_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_student_profiles_class_grade_id_class_grades', 'class_grades', ['class_grade_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_student_profiles_section_id_sections', 'sections', ['section_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_profiles_section_id_sections', type_='foreignkey')
        batch_op.drop_constraint('fk_student_profiles_class_grade_id_class_grades', type_='foreignkey')

    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_subjects_tenant_id'))

    op.drop_table('teacher_subjects')
    with op.batch_alter_table('teacher_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_sections_tenant_id'))

    op.drop_table('teacher_sections')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_class_grade_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sections_class_grade_id'))

    op.drop_table('sections')
    with op.batch_alter_table('class_grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_grades_tenant_id'))

    op.drop_table('class_grades')
    # ### end Alembic commands ###
