"""add chapters and link resources/quizzes to chapters

Revision ID: d9e1a2b4c630
Revises: c3d8e5f7a112
Create Date: 2026-08-26 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.mixins  # GUID custom type, referenced by autogenerated columns


# revision identifiers, used by Alembic.
revision: str = 'd9e1a2b4c630'
down_revision: Union[str, Sequence[str], None] = 'c3d8e5f7a112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'chapters',
        sa.Column('tenant_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('course_id', app.models.mixins.GUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('id', app.models.mixins.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['course_id'], ['courses.id']),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('course_id', 'title', name='uq_chapter_course_title'),
    )
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapters_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapters_course_id'), ['course_id'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', app.models.mixins.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_resources_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_foreign_key('fk_resources_chapter_id', 'chapters', ['chapter_id'], ['id'])
        # Widen the resource_type CHECK constraint (SQLite enums are CHECK-backed) to admit the
        # new content types used by the chapter view.
        batch_op.alter_column(
            'resource_type',
            existing_type=sa.Enum('LINK', 'DOCUMENT', name='resourcetype'),
            type_=sa.Enum('LINK', 'DOCUMENT', 'VIDEO', 'NOTES', 'WORKSHEET', name='resourcetype'),
            existing_nullable=False,
        )

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', app.models.mixins.GUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quizzes_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_foreign_key('fk_quizzes_chapter_id', 'chapters', ['chapter_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quizzes_chapter_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_quizzes_chapter_id'))
        batch_op.drop_column('chapter_id')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column(
            'resource_type',
            existing_type=sa.Enum('LINK', 'DOCUMENT', 'VIDEO', 'NOTES', 'WORKSHEET', name='resourcetype'),
            type_=sa.Enum('LINK', 'DOCUMENT', name='resourcetype'),
            existing_nullable=False,
        )
        batch_op.drop_constraint('fk_resources_chapter_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_resources_chapter_id'))
        batch_op.drop_column('chapter_id')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapters_course_id'))
        batch_op.drop_index(batch_op.f('ix_chapters_tenant_id'))
    op.drop_table('chapters')
